### PR TITLE
Binaries cleanup

### PR DESCRIPTION
**Pull request by fnunnari**
Removing unneeded binaries from the lib directory, as soon as we realize that they are automatically downloaded by gradle.

### CODE REVIEW

**Comment by fnunnari** [comment]
Identified the list of JARs that are _NOT_ downloaded by Gradle:
```
JCup.jar
JFlex.jar  
# For package dark...
JARVIS-API.jar  
# For import main.speechrecognition.audioproviders.Audible;
watson.jar 
# For import de.dfki.stickman3D.Stickman3D;
Stickman.jar  
# For import edu.cmu.sphinx.frontend.util.Microphone;
sphinx4.jar 
# For import de.affect.manage.AffectManager;
affect.jar  
# For import javax.mail.Authenticator;
javax.mail.jar 
# import com.cereproc.cerevoice_eng.SWIGTYPE_p_CPRCEN_engine;
cerevoice_eng.jar  
# import marytts.client.MaryClient;
marytts-client-5.1.2-jar-with-dependencies.jar  
# import org.ujmp.core.collections.ArrayIndexList;
ujmp-complete-0.2.5.jar 
```

However, some other jars might be loaded at run-time only on request.

**Comment by fnunnari** [comment]
I suspect that the two following files are loaded at runtime by the sphinx engine:

```
TIDIGITS_8gau_13dCep_16k_40mel_130Hz_6800Hz.jar
WSJ_8gau_13dCep_16k_40mel_130Hz_6800Hz.jar
```

@SceneMaker, do you know if they are still needed by some plugin/extension?

**Review by algor1th — CHANGES_REQUESTED** [review]
Contains commits not related to the description of the PR.
You can remove them via interactive rebase.

**Comment by fnunnari** [comment]
Was wrongly creating the branch from another branch, rather than master. Closing this and removing.

**Pull request closed without merging**
